create table app_user (
    created_at timestamp not null,
    username varchar(30) not null unique,
    id varchar(64) not null,
    password_hash varchar(255) not null,
    primary key (id)
);

create table chat_session (
    created_at timestamp not null,
    updated_at timestamp not null,
    id varchar(36) not null,
    user_id varchar(64) not null,
    primary key (id)
);

create table document_chunk (
    created_at timestamp not null,
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    title varchar(80) not null,
    content varchar(3000) not null,
    primary key (id)
);

create table document_chunk_tags (
    document_chunk_id bigint not null,
    tags varchar(255)
);

create table evaluation_case (
    created_at timestamp not null,
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    feedback varchar(500),
    question varchar(500) not null,
    primary key (id)
);

create table evaluation_case_expected_keywords (
    evaluation_case_id bigint not null,
    expected_keywords varchar(255)
);

create table session_message (
    message_order integer not null,
    created_at timestamp not null,
    role varchar(20) not null,
    session_id varchar(36) not null,
    content text,
    primary key (message_order, session_id)
);

create table trace_event (
    created_at timestamp not null,
    id bigint generated by default as identity,
    stage varchar(30) not null,
    session_id varchar(36) not null,
    user_id varchar(64) not null,
    message varchar(500) not null,
    attributes text,
    primary key (id)
);

alter table document_chunk_tags
    add constraint fk_document_chunk_tags_document_chunk
    foreign key (document_chunk_id) references document_chunk;

alter table evaluation_case_expected_keywords
    add constraint fk_evaluation_keywords_evaluation_case
    foreign key (evaluation_case_id) references evaluation_case;

alter table session_message
    add constraint fk_session_message_chat_session
    foreign key (session_id) references chat_session;

create index idx_document_chunk_user_id on document_chunk(user_id);
create index idx_chat_session_user_updated on chat_session(user_id, updated_at);
create index idx_trace_event_user_session_created on trace_event(user_id, session_id, created_at);
create index idx_trace_event_user_created on trace_event(user_id, created_at);
create index idx_evaluation_case_user_created on evaluation_case(user_id, created_at);
