alter table app_user add column role varchar(20) not null default 'USER';
alter table app_user add column status varchar(20) not null default 'ACTIVE';

create table chat_message (
    id bigint generated by default as identity,
    session_id varchar(36) not null,
    user_id varchar(64) not null,
    role varchar(20) not null,
    content text not null,
    created_at timestamp not null,
    primary key (id)
);

create table audit_log (
    id bigint generated by default as identity,
    user_id varchar(64),
    action varchar(80) not null,
    resource_type varchar(80) not null,
    resource_id varchar(120),
    request_id varchar(64),
    attributes text,
    created_at timestamp not null,
    primary key (id)
);

create table evaluation_run (
    id bigint generated by default as identity,
    case_id bigint not null,
    user_id varchar(64) not null,
    answer text not null,
    retrieval_hit boolean not null,
    citation_present boolean not null,
    keyword_match boolean not null,
    has_unsupported_claims boolean not null,
    score double precision not null,
    prompt_version varchar(80),
    model_version varchar(80),
    retrieval_version varchar(80),
    summary varchar(500),
    created_at timestamp not null,
    primary key (id)
);

create index idx_chat_message_user_session_created on chat_message(user_id, session_id, created_at);
create index idx_audit_log_user_created on audit_log(user_id, created_at);
create index idx_audit_log_request_id on audit_log(request_id);
create index idx_evaluation_run_user_created on evaluation_run(user_id, created_at);
