create table agent_run (
    id varchar(36) not null,
    session_id varchar(36),
    user_id varchar(64) not null,
    status varchar(20) not null,
    task_description varchar(1000) not null,
    final_answer text,
    error_message varchar(1000),
    max_steps integer not null default 20,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id)
);

create table agent_step (
    id bigint generated by default as identity,
    run_id varchar(36) not null,
    step_index integer not null,
    type varchar(20) not null,
    content text,
    tool_name varchar(100),
    tool_input text,
    tool_result text,
    created_at timestamp not null,
    primary key (id)
);

create index idx_agent_run_user_created on agent_run(user_id, created_at);
create index idx_agent_run_session on agent_run(session_id);
create index idx_agent_step_run on agent_step(run_id);
