create table task_item (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    title varchar(200) not null,
    description text,
    priority varchar(10) not null default 'MEDIUM',
    status varchar(20) not null default 'PENDING',
    due_date timestamp,
    completed_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id)
);

create table reminder_item (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    title varchar(200) not null,
    remind_at timestamp not null,
    status varchar(20) not null default 'PENDING',
    note text,
    created_at timestamp not null,
    primary key (id)
);

create table note_item (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    title varchar(200) not null,
    content text not null,
    tags varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id)
);

create table personal_memory (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    mem_key varchar(100) not null,
    mem_value text not null,
    category varchar(50),
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id)
);

create unique index idx_personal_memory_user_key on personal_memory(user_id, mem_key);

create table tool_invocation (
    id bigint generated by default as identity,
    run_id varchar(36),
    user_id varchar(64) not null,
    tool_name varchar(100) not null,
    tool_input text,
    tool_output text,
    risk_level varchar(10) not null default 'LOW',
    status varchar(20) not null default 'SUCCESS',
    duration_ms bigint,
    error_message varchar(1000),
    created_at timestamp not null,
    primary key (id)
);

create index idx_tool_invocation_run on tool_invocation(run_id);
create index idx_tool_invocation_user_created on tool_invocation(user_id, created_at);
create index idx_task_item_user_status on task_item(user_id, status);
create index idx_reminder_item_user_status on reminder_item(user_id, status);
create index idx_note_item_user_created on note_item(user_id, created_at);
