create table tool_approval (
    id bigint generated by default as identity,
    run_id varchar(36) not null,
    step_index int not null,
    tool_name varchar(100) not null,
    tool_input text,
    status varchar(20) not null default 'PENDING',
    user_id varchar(64) not null,
    created_at timestamp not null,
    primary key (id)
);

create index idx_tool_approval_run on tool_approval(run_id);
create index idx_tool_approval_status on tool_approval(status);
